# This is a Dependabot configuration file for automating dependency updates.
# The configuration is set to version 2 of the Dependabot schema.
# It defines quarterly grouped updates for the GitHub Actions ecosystem.
# The update configuration includes:
# - The directory to scan for dependencies (root directory in this case).
# - A quarterly schedule with a short update cooldown.
# - Allowing both direct and indirect updates for all packages.
# - Grouping all action version updates into one pull request.

version: 2
updates:
    - package-ecosystem: github-actions
      cooldown:
          default-days: 3
          include: ["*"]
      directory: /
      schedule:
          interval: quarterly
          time: "05:30"
          timezone: "America/Detroit"
      assignees: ["Nick2bad4u"]
      allow:
          # Allow both direct and indirect updates for all packages
          - dependency-type: "all"
      labels:
          - "github-actions"
          - "dependabot"
          - "dependencies"
      commit-message:
          prefix: "[ci][skip-ci]"
          prefix-development: "[ci][skip-ci]"
          include: "scope"
      groups:
          github-actions:
              applies-to: version-updates
              patterns:
                  - "*"
